### ISSUE TITLE
NServiceBus UseTransport not working after upgrading to .NET 6

### ISSUE THREAD

**Issue by rineshpk** [Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus#376]
Below code for configuring Azure service bus as the transport in function startup is breaking after upgrading the project to .NET 6

```
var transport = configuration.AdvancedConfiguration.UseTransport<AzureServiceBusTransport>();
           transport.ConnectionString(<connection-string>);
```
Everything was working fine in .NET Core 3.1 and Azure function version 3.0. Recently I upgrade the project to .NET 6 and Function version to 4.0. After the upgrade, `functionEndpoint.Process()` is throwing a null reference exception.

If the UseTransport code is commented out in function startup, no exception is thrown and the messages are getting processed successfully.

Stack trace:

`at NServiceBus.AzureFunctions.InProcess.ServiceBus.PipelineInvoker.PushFailedMessage(ErrorContext errorContext) in /_/src/NServiceBus.AzureFunctions.InProcess.ServiceBus/Serverless/TransportWrapper/PipelineInvoker.cs:line 34 at NServiceBus.FunctionEndpoint.<Process>d__5.MoveNext() in /_/src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionEndpoint.cs:line 122 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at NServiceBus.FunctionEndpoint.<ProcessNonTransactional>d__3.MoveNext() in /_/src/NServiceBus.AzureFunctions.InProcess.ServiceBus/FunctionEndpoint.cs:line 75 at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at LD.ICE.Daemon.Function.ASBTrigger.SyncEventsClient.<Run>d__2.MoveNext() in C:\Repos\IDSPrototype\LD.ICE.Daemon.Function.FuncApp\ASBTrigger\SyncEventsClient.cs:line 23`

**Comment by mikeminutillo** [comment]
@rineshpk you do not need to call `UseTransport<>()` directly as this is already done for you in the `ServiceBusTriggeredEndpointConfiguration` constructor.

You can access the configured transport with the `configuration.Transport` property if you need to. Is there something that you need that isn't covered by this?

**Comment by rineshpk** [comment]
@mikeminutillo Is automatic provisioning of topic and subscription covered by this? After I had added `UseTransport<AzureServiceBusTransport>()`, NServiceBus automatically created the topic and subscription for me. So I'm confused to use `UseTransport<>()` in the configuration or not.

**Comment by mikeminutillo** [comment]
It will provision topics and subscriptions when the endpoint is initially created, which happens when the first message arrives. Unfortunately, this creates a chicken and egg problem. The endpoint cannot create the topology until a message arrives, and a message cannot arrive until the topology is set up. This why we recommend to [use the `asb-transport` command line tool to provision the target environment](https://docs.particular.net/nservicebus/hosting/azure-functions-service-bus/?#preparing-the-azure-service-bus-namespace) rather than rely on NServiceBus installers to do it.

You should not call `UseTransport<>()` for your functions configuration. We [do it for you](https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/blob/release-2.0/src/NServiceBus.AzureFunctions.InProcess.ServiceBus/ServiceBusTriggeredEndpointConfiguration.cs#L149), and we intercept things so that the transport is not running continuously to receive messages, but instead waits for the triggered function to pass it a message.

**Comment by rineshpk** [comment]
Thank you @mikeminutillo . I can create the topology, and it resolves the issue.

**Comment by mikeminutillo** [comment]
Thanks for letting me know @rineshpk 

I have raised https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/issues/377 to record that this issue can occur, as we should be able to detect this situation and warn users when it happens.
