### ISSUE TITLE
Use function hosting runtime for acceptance tests

### ISSUE THREAD

**Issue by timbussmann** [Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus#60]
The acceptance tests for the azure functions support are manually invoking the trigger-method of the function under test via a method call, providing the required parameters (e.g. the ASB message object) directly. This means that the actual trigger is not used to read messages from the queue but the invocation happens manually.
In addition, since the function is not hosted directly in the Azure Functions environment, the assembly scanning and AssemblyLoadContexts are not exactly the same way as a deployed function.

This makes it more difficult to reproduce production environment scenarios in tests and can hide potential bugs during the acceptance tests.

Azure functions are locally hosted using the func.exe which can be obtained using the [Azure Functions Core Tools](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local?tabs=windows%2Ccsharp%2Cbash). Hosting the test functions using the actual host would make testing certain behaviors more difficult as the test context typically used to store test-related information wouldn't be available in the functions hosting process and all assertions would have to be done using black-box-testing approaches, verifying the function behavior solely from external observation.

**Comment by andreasohlund** [comment]
As part of releasing v3 we did some minor improvements to testing:

- Make sure we run all tests for both supported transaction modes
- Emulate the function host by triggering the function by sending a real message to azure service bus (needed to make sure atomic sends with receive works)

This issue is still very relevant since:

- We don't test the actual binding done by the host. (There are manual test projects for host v3 and v4)
- The current emulation of the host would not catch issues in the actual host like the recent one we had with broken DI registrations

In addition to this issue, we should consider adding actual deployments to azure to our test suite since the emulator from MS is likely not behaving identically as the runtime on Azure

**Comment by SeanFeldman** [comment]
> we should consider adding actual deployments to azure to our test suite since the emulator from MS is likely not behaving identically as the runtime on Azure

What emulator was used, @andreasohlund?

**Comment by andreasohlund** [comment]
We just created a basic one ourselfves https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/blob/master/src/ServiceBus.AcceptanceTests/FunctionEndpointComponent.cs

**Comment by SeanFeldman** [comment]
What MS emulator you’re referring to in this?
> emulator from MS is likely not behaving identically as the runtime on Azure

**Comment by DavidBoike** [comment]
@SeanFeldman the func.exe included in the Functions SDK. Though even if it is technically different than what's running in Azure, I'm sure that would be better than what we're doing now.

**Comment by SeanFeldman** [comment]
I would not refer to `func.exe` from the [Functions Core Tools](https://docs.microsoft.com/en-us/azure/azure-functions/functions-run-local) as an emulator.

And yes, using the runtime would be better. We have not gone that route originally but it was the intent.

**Comment by andreasohlund** [comment]
Done in https://github.com/Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus/pull/596
