### ISSUE TITLE
Allow endpoint configuration to use IConfiguration

### ISSUE THREAD

**Issue by seankearney** [Particular/NServiceBus.AzureFunctions.InProcess.ServiceBus#95]
In my Azure Function I am heavily using the `IConfiguration`. More specifically, my connection string to Azure Service Bus is accessed via App Config Service, which in turns gets the value from Key Vault. Ultimately, my actual connection string is available in the `IConfiguration`.  However, based on what I'm seeing it appears that NSB must load the configuration string from an environment variable. See [here](https://github.com/Particular/NServiceBus.AzureFunctions.ServiceBus/blob/b0b734fefa825983bb5d384100bcd71a24a6bb34/src/NServiceBus.AzureFunctions.ServiceBus/ServiceBusTriggeredEndpointConfiguration.cs#L32). Ideally, I'd like to pass you a settings 'key' and the value is fetched from an `IConfiguration`.

cc @SeanFeldman

**Comment by SeanFeldman** [comment]
Azure App Config service will not work. Functions [documentation](https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#customizing-configuration-sources) says the following: 

> For function apps running in the Consumption or Premium plans, modifications to configuration values used in triggers can cause scaling errors. Any changes to these properties by the FunctionsStartup class results in a function app startup error.

**Comment by jenspettersson** [comment]
Sorry for using an rather old issue, but we're having a similar issue. We want to use User Secrets when developing due to the fact that we use one Azure Service Bus namespace/instance per developer and want to store the user specific connection string as a user secret.

It fails as the code tries to fetch the connection string from an environment variable, as mentioned by @seankearney. 

We could probably just set an environment variable on each developer machine, but we were hoping to be able to utilize the dotnet user-secrets tools instead...

Any ideas?

**Comment by seankearney** [comment]
@jenspettersson It has been a long time since we tried getting "User Secrets" to work in a function app. Ultimately we gave up on the idea and resorted to using the `local.settings.json` file, but we added a `.gitignore` entry to that to prevent it from making its way into source control.

**Comment by SeanFeldman** [comment]
This issue is primarily focused on providing the connection string to ASB via `IConfiguration`.  This is currently not possible with the link to the documentation [here](https://github.com/Particular/NServiceBus.AzureFunctions.ServiceBus/issues/95#issuecomment-717618825). Also, see [this public issue](https://github.com/Azure/azure-functions-host/issues/4464) for more context.

Anyone interested in local development using local settings can do so by storing their settings, including ASB connection string, using [`local.settings.json` file](https://docs.microsoft.com/en-us/azure/azure-functions/functions-develop-vs#local-settings-file), as @seankearney [has described](https://github.com/Particular/NServiceBus.AzureFunctions.ServiceBus/issues/95#issuecomment-767164062).
